# Server Configuration
server.port=8080

# Database Configuration (MongoDB)
spring.data.mongodb.uri=mongodb://localhost:27017/hms?retryWrites=false

# Spring MVC/Jackson Configuration
spring.jackson.deserialization.fail-on-unknown-properties=false

# Compression Settings
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain

# Logging Configuration
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb=INFO
logging.level.com.hms.backend=DEBUG
